### ISSUE TITLE
Original TB-303

### ISSUE THREAD

**Issue by pX5374** [sunflowr/recpu#6]
Tried to flash my original TB-303 but after the sysex dump was successful the device reboots and the missing emulator firmware status message appears again. no luck it keeps the firmware. any ideas? thanks!

**Comment by sunflowr** [comment]
Sorry for the taking so long to answer!
Hm. My best guess would be that the transferring of the 303 firmware wasn't successful.. does your SysEx software have any control over transfer speed / delay or similar or any other settings you could try?
What MIDI interface are you using?

**Comment by RoelofBerg** [comment]
Also sorry for the late answer. I had to change some transfer setting to transfer in a more careful way. It took several minutes then but succeeded (vs. before seconds but did not succeed). I forgot the exact setting I changed, I think it was something like the packet size to the smallest value. And maybe there was a little hint in the manual pointing to this value (?). This setting was done in the tool I used for the sysex download. Also trying another sysex tool might help.

**Comment by sunflowr** [comment]
Great to hear you solved it. Can't remember if I put some hint about it in the manual or not.. but will check and see if I can make it more clear.

Will close the issue as it sounds like it's been resolved. Please post again if any more issues come up. :)

**Comment by pX5374** [comment]
Yeah apparently I had the wrong file to upload. I tried every file I could find on the interwebs and got it working :). Ant remember the settings but happy user now with a working 303 with midi (wanted to get rid of the buggy sonicpotion cpu)

**Comment by sunflowr** [comment]
Good to hear :)

**Comment by yooseywoosey** [comment]
I'm having a similar problem getting my new RE-CPU to work on my TB-303. I've installed the bootloader (1.4.3.syx), I then re-booted holding C and got the led's scrolling back and forth. I then transferred the reemu_1.4.3.syx software. It then re-boots to the waiting for missing firmware message. I'm using SysEx Librarian on Mac and have tried many settings between fast and slow transfers and multiple buffer sizes. I've also tried 2 different midi interfaces using as many variations of the settings as I can think of, I just can't get it to work - it always ends on the missing firmware message. 

One thing to note is before I started any transfers (and also now I have attempted to transfer the software) the led's are lit as they say they should be in the manual  for the missing firmware message, but in addition to those, I have the 'Time Mode' led lit. Also, when installing the software, instead of the C note being lit, the 'Pitch Mode' led lights up instead.

I've installed quite a few mods and CPU upgrades on various bits of kit, so have 'some' skills in the installation of such products, but I'm by no means an expert and it's very possible I have made an error, somewhere. If anyone has any ideas on how to make this work, I'd be most grateful.

**Comment by TBass303** [comment]
Have pixie installed in my tb-303 due to original cpu issues. Installed tb303.syx Firmware, bootloader 1.4.3, and reemu 1.4.3. Had a hard time finding the firmware and installed it after bootloader and reemu. Tb303 working but a few LED’s aren’t lighting up (worked before pixie install). Switches where LED’s do not fire work without issues. Can this be fixed?
